/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fuxi_javaagent_contentobjects_jnotify_macosx_JNotify_macosx */

#ifndef _Included_com_fuxi_javaagent_contentobjects_jnotify_macosx_JNotify_macosx
#define _Included_com_fuxi_javaagent_contentobjects_jnotify_macosx_JNotify_macosx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fuxi_javaagent_contentobjects_jnotify_macosx_JNotify_macosx
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fuxi_javaagent_contentobjects_jnotify_macosx_JNotify_1macosx_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_fuxi_javaagent_contentobjects_jnotify_macosx_JNotify_macosx
 * Method:    nativeAddWatch
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fuxi_javaagent_contentobjects_jnotify_macosx_JNotify_1macosx_nativeAddWatch
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fuxi_javaagent_contentobjects_jnotify_macosx_JNotify_macosx
 * Method:    nativeRemoveWatch
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fuxi_javaagent_contentobjects_jnotify_macosx_JNotify_1macosx_nativeRemoveWatch
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fuxi_javaagent_contentobjects_jnotify_macosx_JNotify_macosx
 * Method:    nativeNotifyLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fuxi_javaagent_contentobjects_jnotify_macosx_JNotify_1macosx_nativeNotifyLoop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
